//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public System.DateTime NgaySinh { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
